### PR TITLE
Improve installation instructions, add Screenshots to Readme.md

### PR DESCRIPTION
**Pull request by Bixilon**
I improved the installation instructions, added all dependencies. Because of #16 I also changed the regex from the principial name to the same as basedn. 

I missed screenshots, so I added 2 to the Readme.md, that everybody can see them (without clicking through the folders)

### CODE REVIEW

**Comment by anklimsk** [comment]
Thank! I'll take this as a basis and refactor the code. Can you help me test the solution on a new branch?

**Comment by Bixilon** [comment]
Sure, what to do?

**Comment by anklimsk** [comment]
I need to check a list of LDAP queries:
Getting a list of name computers
```(&(objectClass=posixAccount)(uid=*$))```

Getting a list of groups
```objectClass=posixGroup```

Getting a list of a groups by member uid
```(&(objectClass=posixGroup)(memberUid=someUid))```

Getting a record by UUID(GUID)
```(&(objectClass=posixAccount)(entryUUID=some-uuid-string))```

The search base for users and computers is known (specified in the settings).
I don't know how to exclude inactive entries in OpenLDAP.
Thanks!

**Comment by Bixilon** [comment]
Yah, ... how to test it?

**Comment by anklimsk** [comment]
I pushed the changes to the "[dev](https://github.com/anklimsk/wpkg-express-2/tree/dev)" branch. 
Application settings can now save with empty access group lists when using alternative directory services (not Active Directory).
Now, when selecting the "Hosts" → "Generate based on LDAP" menu item, the list (1) should contain the names of computers obtained from the Directory Service via LDAP (https://anklimsk.github.io/wpkg-express-2/presentation/#29). Please install the application from the "[dev](https://github.com/anklimsk/wpkg-express-2/tree/dev)" branch and check if the list of computer names is not empty.

**Comment by Bixilon** [comment]
Sorry for the late response. I am currently not able to test it. I will do so in the next days (or weeks).

But I think this is not really important for the merge request. Could you please merge this and we discuss the testing somewhere else? i would appreciate it.

Thanks

**Comment by anklimsk** [comment]
Hello! Ok, I'll include these changes in the release. If you have any problems, open Issue. Thank!

**Pull request closed without merging**
